services:
  springapp:
    container_name: springapp
    image: tortitas-con-sirope:1.0.0
    build: .
    ports:
      - 8787:8787
    environment:
      - DATABASE_URL=jdbc:postgresql://games:5432/postgres
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=postgres
      - SPRING_MONGODB_URI=mongodb+srv://noor:Cheema_2002@cluster0.8mujuld.mongodb.net/?appName=Cluster0
      - TELEGRAM_BOT_TOKEN=8693576752:AAF-cq5pD0jOFHYnRobtD9p8BoCy26gQLPM
      - TELEGRAM_BOT_USERNAME=SiropeGamersBot
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SERVER_PORT=8787
      - SPRING_SECURITY_USER_NAME=disable
      - SPRING_AUTOCONFIGURE_EXCLUDE=org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration
      - SPRING_AI_OLLAMA_BASE_URL=http://host.docker.internal:11434/
    depends_on:
      - games
  games:
    container_name: games
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
      - PGDATA=/var/lib/postgresql
    restart: always