spring.application.name=TFG
spring.ai.ollama.chat.options.model = qwen3-embedding
spring.ai.model.embedding=qwen3-embedding
server.port = 8087
spring.ai.ollama.base-url=http://127.0.0.1:11434

spring.ai.ollama.init.pull-model-strategy=never