spring.application.name=TFG

spring.ai.ollama.embedding.options.model=qwen3-embedding
server.port = 8087
spring.ai.ollama.base-url=http://127.0.0.1:11434
spring.ai.ollama.init.pull-model-strategy=never

#telegrambot
telegram.bot.token=8693576752:AAF-cq5pD0jOFHYnRobtD9p8BoCy26gQLPM
telegram.bot.username=SiropeGamersBot
spring.data.mongodb.auto-index-creation=true

#PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/games.db
spring.datasource.username=user
spring.datasource.password=pass
