spring.application.name=TFG

#spring.ai.ollama.embedding.options.model=qwen3-embedding
spring.ai.ollama.embedding.options.model=nomic-embed-text
server.port=8087
spring.ai.ollama.base-url=http://127.0.0.1:11434
spring.ai.ollama.init.pull-model-strategy=never

#mongodb
spring.mongodb.uri=mongodb+srv://noor:Cheema_2002@cluster0.8mujuld.mongodb.net/?appName=Cluster0
spring.mongodb.database=pruebatfg

#telegrambot
telegram.bot.token=8693576752:AAF-cq5pD0jOFHYnRobtD9p8BoCy26gQLPM
telegram.bot.username=SiropeGamersBot

#PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/games.db
spring.datasource.username=user
spring.datasource.password=pass